name: Release DMG

on:
  push:
    tags:
      - '*'

jobs:
  build-and-package:
    runs-on: macos-13

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build DMG
        run: ./scripts/build_dmg.sh

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-display-dmg
          path: build/desktop-display.dmg
          if-no-files-found: error

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/desktop-display.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
